/**
 * OrbitanOS — Task Controller Automated Test Suite
 * Phase A validation: transition matrix, optimistic locking, idempotency,
 * permission enforcement, and tenant isolation.
 *
 * Creates a temporary task, runs assertions, cleans up. Audit-log entries
 * are immutable by design (admin-only delete) and tagged "TESTSUITE" so
 * an admin can purge them; all Task/TaskAssignment/WorkReview records are
 * hard-deleted in a finally block.
 */
import { createClientFromRequest } from 'npm:@base44/sdk@0.8.31';

Deno.serve(async (req) => {
  const base44 = createClientFromRequest(req);
  const results = [];
  const cleanup = []; // {entity, id} to delete at the end
  let createdTaskId = null;

  const assert = (name, condition, detail) => {
    results.push({ test: name, pass: !!condition, detail: detail || null });
    return condition;
  };

  let user = null;
  try {
    user = await base44.auth.me();
  } catch (e) {
    return Response.json({ error: 'auth required', message: e.message }, { status: 401 });
  }
  if (!user) {
    return Response.json({ error: 'no authenticated user' }, { status: 401 });
  }

  const tenantId = user.data?.tenant_id || user.tenant_id;
  const report = {
    user: { id: user.id, role: user.role, name: user.full_name, tenant_id: tenantId },
    started_at: new Date().toISOString(),
    tests: results,
  };

  if (!tenantId) {
    assert('user.tenant_id resolved', false, 'User has no tenant_id — cannot run lifecycle tests');
    report.tests = results;
    report.summary = summarize(results);
    return Response.json(report);
  }

  const TC = 'taskController';
  const invoke = (payload) => base44.functions.invoke(TC, payload)
    .then(r => ({ ok: true, status: r.status || 200, data: r.data || r }))
    .catch(e => ({ ok: false, status: e.response?.status || 500, data: e.response?.data || { error: e.message } }));

  try {
    // ── T1: Tenant isolation — createTask with foreign tenant_id must be blocked ──
    const iso = await invoke({ action: 'createTask', tenant_id: 'foreign-tenant-zzz', title: 'TESTSUITE iso' });
    assert('T1 tenant isolation blocks foreign tenant create', iso.status === 403 || iso.data?.error?.includes('Permission denied'), `status=${iso.status}`);

    // ── T2: createTask valid (own tenant) — may fail if role lacks create permission ──
    const createRes = await invoke({
      action: 'createTask',
      tenant_id: tenantId,
      title: 'TESTSUITE—lifecycle (auto-cleanup)',
      description: 'Auto-generated by taskControllerTestSuite. Safe to delete.',
      priority: 'low',
      verification_mode: 'none',
    });

    if (!createRes.ok || !createRes.data?.task?.id) {
      assert('T2 createTask in own tenant', false, `create failed: ${JSON.stringify(createRes.data)}`);
      report.summary = summarize(results);
      return Response.json(report);
    }
    createdTaskId = createRes.data.task.id;
    cleanup.push({ entity: 'Task', id: createdTaskId });
    assert('T2 createTask in own tenant succeeds', true, `task_id=${createdTaskId} status=${createRes.data.task.status}`);

    let task = createRes.data.task;
    assert('T2a initial status is draft (no agents assigned)', task.status === 'draft', `status=${task.status}`);
    assert('T2b initial version is 1', task.version === 1, `version=${task.version}`);

    // ── T3: Forbidden transition (draft → verified) must be rejected ──
    const forbidden = await invoke({ action: 'transition', task_id: createdTaskId, target_status: 'verified', version: task.version });
    const forbPass = forbidden.status === 422 && forbidden.data?.error?.includes('Invalid transition');
    assert('T3 forbidden transition draft→verified rejected (422)', forbPass, `status=${forbidden.status} err=${forbidden.data?.error}`);
    assert('T3a response lists allowed_targets', Array.isArray(forbidden.data?.allowed_targets) && forbidden.data.allowed_targets.includes('cancelled'), `targets=${JSON.stringify(forbidden.data?.allowed_targets)}`);

    // ── T4: Required field — draft→cancelled without reason must be rejected ──
    const noReason = await invoke({ action: 'transition', task_id: createdTaskId, target_status: 'cancelled', version: task.version });
    assert('T4 draft→cancelled without reason rejected (422)', noReason.status === 422 && noReason.data?.error?.includes('reason'), `status=${noReason.status} err=${noReason.data?.error}`);

    // ── T5: Optimistic locking — stale version must be rejected (409) ──
    const stale = await invoke({ action: 'transition', task_id: createdTaskId, target_status: 'cancelled', version: 999, reason: 'test stale' });
    assert('T5 optimistic lock rejects stale version (409)', stale.status === 409 && stale.data?.error?.includes('Stale version'), `status=${stale.status} err=${stale.data?.error}`);

    // ── T6: Valid transition draft→cancelled with reason + idempotency key ──
    const idemKey = `testsuite-${createdTaskId}-${Date.now()}`;
    const valid = await invoke({ action: 'transition', task_id: createdTaskId, target_status: 'cancelled', version: task.version, reason: 'TESTSUITE cancel', idempotency_key: idemKey });
    assert('T6 valid transition draft→cancelled succeeds', valid.ok && valid.data?.task?.status === 'cancelled', `status=${valid.status} task.status=${valid.data?.task?.status}`);
    if (valid.data?.task) {
      assert('T6a version incremented after transition', valid.data.task.version === (task.version + 1), `new version=${valid.data.task.version}`);
      assert('T6b cancelled_date set', !!valid.data.task.cancelled_date, `cancelled_date=${valid.data.task.cancelled_date}`);
    }

    // ── T7: Idempotency replay — same key returns current state without re-processing ──
    const replay = await invoke({ action: 'transition', task_id: createdTaskId, target_status: 'cancelled', version: valid.data?.task?.version, reason: 'TESTSUITE cancel', idempotency_key: idemKey });
    assert('T7 idempotent replay returns idempotent=true', replay.ok && replay.data?.idempotent === true, `status=${replay.status} idempotent=${replay.data?.idempotent}`);

    // ── T8: getAllowedTransitions for cancelled task returns empty (no source in matrix) ──
    const allowed = await invoke({ action: 'getAllowedTransitions', task_id: createdTaskId });
    assert('T8 cancelled task has no allowed transitions', allowed.ok && Array.isArray(allowed.data?.allowed_transitions) && allowed.data.allowed_transitions.length === 0, `count=${allowed.data?.allowed_transitions?.length}`);

    // ── T9: Permission enforcement — assignAgent requires manager role ──
    const assignRes = await invoke({ action: 'assignAgent', task_id: createdTaskId, agent_id: user.id, assignee_name: user.full_name, assignment_role: 'responsible' });
    const isManagerRole = ['admin', 'tenant_admin', 'outlet_manager', 'supervisor'].includes(user.role);
    if (isManagerRole) {
      assert('T9 manager can assign agent', assignRes.ok && assignRes.data?.assignment?.id, `status=${assignRes.status}`);
      if (assignRes.data?.assignment?.id) cleanup.push({ entity: 'TaskAssignment', id: assignRes.data.assignment.id });
    } else {
      assert('T9 non-manager blocked from assignAgent (403)', assignRes.status === 403, `status=${assignRes.status} role=${user.role}`);
    }

  } catch (e) {
    assert('suite completed without runtime error', false, e.message);
  } finally {
    // ── Cleanup: hard-delete all created records (service role bypasses RLS) ──
    for (const c of cleanup) {
      try {
        if (c.entity === 'TaskAssignment') await base44.asServiceRole.entities.TaskAssignment.delete(c.id);
        if (c.entity === 'Task') {
          // delete child assignments + reviews first
          try {
            const kids = await base44.asServiceRole.entities.TaskAssignment.filter({ task_id: c.id });
            await Promise.all(kids.map(k => base44.asServiceRole.entities.TaskAssignment.delete(k.id).catch(() => {})));
          } catch {}
          try {
            const revs = await base44.asServiceRole.entities.WorkReview.filter({ target_record_id: c.id });
            await Promise.all(revs.map(r => base44.asServiceRole.entities.WorkReview.delete(r.id).catch(() => {})));
          } catch {}
          await base44.asServiceRole.entities.Task.delete(c.id);
        }
      } catch (e) { /* best-effort cleanup */ }
    }
  }

  report.tests = results;
  report.summary = summarize(results);
  report.completed_at = new Date().toISOString();
  return Response.json(report);
});

function summarize(results) {
  const total = results.length;
  const passed = results.filter(r => r.pass).length;
  const failed = total - passed;
  return { total, passed, failed, pass_rate: total ? `${Math.round((passed / total) * 100)}%` : '0%' };
}