import React, { useState, useMemo } from 'react';
import { Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { useTenant } from '@/lib/use-tenant.jsx';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Skeleton } from '@/components/ui/skeleton';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import OrbitanLogo from '@/components/layout/OrbitanLogo';
import { useToast } from '@/components/ui/use-toast';
import { Shield, Search, Download, ArrowLeft, FileText, Filter, LogOut, Eye, FileArchive, Loader2 } from 'lucide-react';

const MODULE_LABELS = {
  finance: 'Finance', inventory: 'Inventory', procurement: 'Procurement',
  workforce: 'Workforce', compliance: 'Compliance', sales: 'Sales',
  scheduling: 'Scheduling', retail: 'Retail', sustainability: 'Sustainability', system: 'System',
};

const SHIELD_STYLES = {
  pass: 'bg-emerald-500/10 text-emerald-600 border-emerald-500/20',
  blocked: 'bg-red-500/10 text-red-600 border-red-500/20',
  override_requested: 'bg-amber-500/10 text-amber-600 border-amber-500/20',
  override_approved: 'bg-blue-500/10 text-blue-600 border-blue-500/20',
  override_denied: 'bg-red-500/10 text-red-600 border-red-500/20',
  not_evaluated: 'bg-slate-500/10 text-slate-500 border-slate-500/20',
};

export default function AuditTrail() {
  const { currentTenant: tenant } = useTenant();
  const { toast } = useToast();
  const [search, setSearch] = useState('');
  const [moduleFilter, setModuleFilter] = useState('all');
  const [outcomeFilter, setOutcomeFilter] = useState('all');
  const [dateFrom, setDateFrom] = useState('');
  const [dateTo, setDateTo] = useState('');
  const [page, setPage] = useState(0);
  const [detailLog, setDetailLog] = useState(null);
  const [bundling, setBundling] = useState(false);
  const pageSize = 25;

  const { data: logs, isLoading } = useQuery({
    queryKey: ['audit-trail', page, moduleFilter, outcomeFilter, dateFrom, dateTo, search],
    queryFn: async () => {
      const filter = {};
      if (moduleFilter !== 'all') filter.module = moduleFilter;
      if (outcomeFilter !== 'all') filter.shield_outcome = outcomeFilter;
      const result = await base44.entities.AuditLog.filter(filter, '-created_date', pageSize + 1, page * pageSize);
      let filtered = result || [];
      if (search.trim()) {
        const term = search.toLowerCase();
        filtered = filtered.filter(l =>
          l.actor_name?.toLowerCase().includes(term) ||
          l.action_type?.toLowerCase().includes(term) ||
          l.target_entity?.toLowerCase().includes(term) ||
          l.details?.toLowerCase().includes(term)
        );
      }
      if (dateFrom) filtered = filtered.filter(l => l.created_date && new Date(l.created_date) >= new Date(dateFrom));
      if (dateTo) filtered = filtered.filter(l => l.created_date && new Date(l.created_date) <= new Date(dateTo + 'T23:59:59'));
      return filtered;
    },
    enabled: !!tenant,
  });

  const hasMore = logs && logs.length > pageSize;
  const displayLogs = hasMore ? logs.slice(0, pageSize) : logs || [];

  const stats = useMemo(() => ({
    total: displayLogs.length,
    blocks: displayLogs.filter(l => l.shield_outcome === 'blocked').length,
    overrides: displayLogs.filter(l => l.shield_outcome?.startsWith('override')).length,
    actors: new Set(displayLogs.map(l => l.actor_id)).size,
  }), [displayLogs]);

  const handleExportBundle = async () => {
    setBundling(true);
    try {
      const res = await base44.functions.invoke('auditBundleGenerator', {
        tenant_id: tenant?.id,
        module: moduleFilter !== 'all' ? moduleFilter : undefined,
        date_from: dateFrom || undefined,
        date_to: dateTo || undefined,
      });
      const bundle = res.data || res;
      const m = bundle.manifest;
      if (!m) throw new Error('Bundle generator returned no manifest.');

      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF();
      doc.setFontSize(16); doc.text('OrbitanOS — Audit Bundle', 14, 20);
      doc.setFontSize(9);
      doc.text(`Bundle ID: ${m.bundle_id}`, 14, 28);
      doc.text(`Tenant: ${m.tenant_id}`, 14, 33);
      doc.text(`Generated: ${new Date(m.generated_at).toLocaleString('en-SG')}`, 14, 38);
      doc.text(`Generated by: ${m.generated_by?.name || 'system'} (${m.generated_by?.role || 'system'})`, 14, 43);
      doc.text(`Integrity Hash: ${m.integrity_hash}`, 14, 48);
      doc.text(`Events: ${m.event_count}  |  Evidence Artifacts: ${m.artifact_count}`, 14, 53);
      doc.text(`Standard: ${m.standard}`, 14, 58);

      doc.setFontSize(11); doc.text('Audit Events', 14, 70);
      doc.setFontSize(8);
      let y = 76;
      (bundle.events || []).forEach((e) => {
        if (y > 272) { doc.addPage(); y = 20; }
        doc.text(`${new Date(e.timestamp).toLocaleString('en-SG')} — ${e.actor_name || 'System'} — ${e.action_type || ''}`, 14, y); y += 5;
        doc.text(`   ${e.target_entity || ''} #${(e.target_record_id || '').slice(-8)} | shield: ${e.shield_outcome || 'n/a'}`, 14, y); y += 7;
      });

      if ((bundle.artifacts || []).length > 0) {
        doc.addPage();
        doc.setFontSize(11); doc.text('Linked Evidence (Artifact Registry)', 14, 20);
        doc.setFontSize(8);
        let ay = 28;
        bundle.artifacts.forEach((a) => {
          if (ay > 272) { doc.addPage(); ay = 20; }
          doc.text(`${a.title} — ${a.artifact_type} — ${a.status}`, 14, ay); ay += 5;
          if (a.storage_url) { doc.text(`   ${a.storage_url}`, 14, ay); ay += 5; }
          ay += 3;
        });
      }

      doc.save(`audit-bundle-${m.bundle_id}.pdf`);
      toast({ title: 'Audit Bundle Generated', description: `${m.event_count} events packaged with integrity hash ${m.integrity_hash.slice(0, 12)}…` });
    } catch (err) {
      toast({ title: 'Bundle generation failed', description: err?.response?.data?.error || err?.message || 'An error occurred.', variant: 'destructive' });
    } finally {
      setBundling(false);
    }
  };

  const handleExport = () => {
    const headers = ['Timestamp', 'Actor', 'Role', 'Action', 'Module', 'Target Entity', 'Record ID', 'Details', 'Shield Outcome', 'IP', 'Justification'];
    const rows = displayLogs.map(l => [
      l.created_date ? new Date(l.created_date).toLocaleString() : '',
      l.actor_name || '', l.actor_role || '', l.action_type || '',
      MODULE_LABELS[l.module] || l.module || '', l.target_entity || '',
      l.target_record_id || '', (l.details || '').replace(/"/g, '""'),
      l.shield_outcome || 'not_evaluated', l.ip_address || '',
      (l.justification || '').replace(/"/g, '""'),
    ]);
    const csv = [headers, ...rows].map(r => r.map(c => `"${c}"`).join(',')).join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `audit-trail-${new Date().toISOString().split('T')[0]}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (!tenant) {
    return <div className="min-h-screen flex items-center justify-center"><p className="text-muted-foreground">Loading workspace...</p></div>;
  }

  return (
    <div className="min-h-screen bg-background flex flex-col">
      <header className="border-b border-border bg-background sticky top-0 z-40">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 py-3 flex items-center justify-between gap-3">
          <div className="flex items-center gap-3">
            <Button variant="ghost" size="icon" asChild><Link to="/company"><ArrowLeft className="w-4 h-4" /></Link></Button>
            <OrbitanLogo size="sm" showOS />
          </div>
          <div className="flex items-center gap-3">
            <Button variant="outline" size="sm" onClick={handleExport} disabled={!displayLogs.length}>
              <Download className="w-4 h-4 mr-1.5" /> Export CSV
            </Button>
            <Button variant="default" size="sm" onClick={handleExportBundle} disabled={bundling}>
              {bundling ? <Loader2 className="w-4 h-4 mr-1.5 animate-spin" /> : <FileArchive className="w-4 h-4 mr-1.5" />} Audit Bundle
            </Button>
            <Button variant="outline" size="sm" onClick={() => base44.auth.logout()} className="gap-1.5 text-xs">
              <LogOut className="w-3.5 h-3.5" /><span className="hidden sm:inline">Sign Out</span>
            </Button>
          </div>
        </div>
      </header>

      <main className="flex-1 max-w-7xl mx-auto w-full px-4 sm:px-6 py-8">
        <div className="mb-6">
          <div className="inline-flex items-center gap-2 bg-primary/10 text-primary px-3 py-1.5 rounded-full text-xs font-semibold mb-3">
            <Shield className="w-3.5 h-3.5" /> SOC 2 Compliance · Regulate
          </div>
          <h1 className="text-2xl sm:text-3xl font-display font-bold text-foreground mb-1">Audit Trail</h1>
          <p className="text-sm text-muted-foreground">Chronological, tamper-proof record of all high-impact actions — procurement approvals, inventory adjustments, governance overrides, and more.</p>
        </div>

        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
          <div className="bg-card border border-border rounded-xl p-4">
            <p className="text-xs text-muted-foreground mb-1">Total Events</p>
            <p className="text-2xl font-display font-bold">{stats.total}</p>
          </div>
          <div className="bg-card border border-border rounded-xl p-4">
            <p className="text-xs text-muted-foreground mb-1">Shield Blocks</p>
            <p className="text-2xl font-display font-bold text-red-600">{stats.blocks}</p>
          </div>
          <div className="bg-card border border-border rounded-xl p-4">
            <p className="text-xs text-muted-foreground mb-1">Overrides</p>
            <p className="text-2xl font-display font-bold text-amber-600">{stats.overrides}</p>
          </div>
          <div className="bg-card border border-border rounded-xl p-4">
            <p className="text-xs text-muted-foreground mb-1">Unique Actors</p>
            <p className="text-2xl font-display font-bold">{stats.actors}</p>
          </div>
        </div>

        <div className="bg-card border border-border rounded-xl p-4 mb-4">
          <div className="flex flex-col md:flex-row gap-3">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
              <Input placeholder="Search actor, action, entity, or details..." value={search} onChange={e => { setSearch(e.target.value); setPage(0); }} className="pl-9" />
            </div>
            <Select value={moduleFilter} onValueChange={v => { setModuleFilter(v); setPage(0); }}>
              <SelectTrigger className="w-full md:w-44"><Filter className="w-4 h-4 mr-1.5 text-muted-foreground" /><SelectValue placeholder="Module" /></SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Modules</SelectItem>
                {Object.entries(MODULE_LABELS).map(([k, l]) => <SelectItem key={k} value={k}>{l}</SelectItem>)}
              </SelectContent>
            </Select>
            <Select value={outcomeFilter} onValueChange={v => { setOutcomeFilter(v); setPage(0); }}>
              <SelectTrigger className="w-full md:w-44"><Shield className="w-4 h-4 mr-1.5 text-muted-foreground" /><SelectValue placeholder="Outcome" /></SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Outcomes</SelectItem>
                <SelectItem value="pass">Pass</SelectItem>
                <SelectItem value="blocked">Blocked</SelectItem>
                <SelectItem value="override_requested">Override Requested</SelectItem>
                <SelectItem value="override_approved">Override Approved</SelectItem>
                <SelectItem value="override_denied">Override Denied</SelectItem>
                <SelectItem value="not_evaluated">Not Evaluated</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="flex gap-3 mt-3">
            <div className="flex-1">
              <label className="text-xs text-muted-foreground block mb-1">From Date</label>
              <Input type="date" value={dateFrom} onChange={e => { setDateFrom(e.target.value); setPage(0); }} />
            </div>
            <div className="flex-1">
              <label className="text-xs text-muted-foreground block mb-1">To Date</label>
              <Input type="date" value={dateTo} onChange={e => { setDateTo(e.target.value); setPage(0); }} />
            </div>
          </div>
        </div>

        <div className="bg-card border border-border rounded-xl overflow-hidden">
          {isLoading ? (
            <div className="p-6 space-y-3">{[...Array(6)].map((_, i) => <Skeleton key={i} className="h-12 w-full" />)}</div>
          ) : displayLogs.length === 0 ? (
            <div className="py-16 text-center">
              <FileText className="w-12 h-12 text-muted-foreground/30 mx-auto mb-3" />
              <p className="text-sm font-medium text-foreground">No audit events found</p>
              <p className="text-xs text-muted-foreground mt-1">Try adjusting your filters.</p>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr className="border-b border-border bg-muted/50">
                    <th className="text-left text-xs font-semibold text-muted-foreground px-4 py-3">Timestamp</th>
                    <th className="text-left text-xs font-semibold text-muted-foreground px-4 py-3">Actor</th>
                    <th className="text-left text-xs font-semibold text-muted-foreground px-4 py-3">Action</th>
                    <th className="text-left text-xs font-semibold text-muted-foreground px-4 py-3">Module</th>
                    <th className="text-left text-xs font-semibold text-muted-foreground px-4 py-3">Target</th>
                    <th className="text-left text-xs font-semibold text-muted-foreground px-4 py-3">Shield</th>
                    <th className="px-4 py-3"></th>
                  </tr>
                </thead>
                <tbody>
                  {displayLogs.map(log => (
                    <tr key={log.id} className="border-b border-border/50 hover:bg-muted/30 transition-colors cursor-pointer" onClick={() => setDetailLog(log)}>
                      <td className="px-4 py-3 text-xs text-muted-foreground whitespace-nowrap">
                        {log.created_date ? new Date(log.created_date).toLocaleString('en-SG', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' }) : '—'}
                      </td>
                      <td className="px-4 py-3">
                        <div className="flex flex-col">
                          <span className="text-sm font-medium text-foreground">{log.actor_name || 'System'}</span>
                          <span className="text-[10px] text-muted-foreground">{log.actor_role || ''}</span>
                        </div>
                      </td>
                      <td className="px-4 py-3 text-xs font-medium text-foreground">{log.action_type?.replace(/_/g, ' ') || '—'}</td>
                      <td className="px-4 py-3 text-xs text-muted-foreground">{MODULE_LABELS[log.module] || log.module || '—'}</td>
                      <td className="px-4 py-3 text-xs text-muted-foreground">
                        <div className="flex flex-col">
                          <span>{log.target_entity || '—'}</span>
                          {log.target_record_id && <span className="text-[10px] font-mono text-muted-foreground/60">#{log.target_record_id.slice(-8)}</span>}
                        </div>
                      </td>
                      <td className="px-4 py-3">
                        <span className={`inline-flex items-center px-2 py-0.5 rounded-md border text-[10px] font-medium ${SHIELD_STYLES[log.shield_outcome] || SHIELD_STYLES.not_evaluated}`}>
                          {log.shield_outcome?.replace(/_/g, ' ') || 'not evaluated'}
                        </span>
                      </td>
                      <td className="px-4 py-3"><Eye className="w-4 h-4 text-muted-foreground" /></td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>

        {!isLoading && displayLogs.length > 0 && (
          <div className="flex items-center justify-between mt-4">
            <p className="text-xs text-muted-foreground">Showing {page * pageSize + 1}–{page * pageSize + displayLogs.length}</p>
            <div className="flex items-center gap-2">
              <Button variant="outline" size="sm" disabled={page === 0} onClick={() => setPage(page - 1)}>Previous</Button>
              <Button variant="outline" size="sm" disabled={!hasMore} onClick={() => setPage(page + 1)}>Next</Button>
            </div>
          </div>
        )}
      </main>

      <Dialog open={!!detailLog} onOpenChange={() => setDetailLog(null)}>
        <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2"><Shield className="w-4 h-4 text-primary" /> Audit Event Detail</DialogTitle>
          </DialogHeader>
          {detailLog && (
            <div className="space-y-4 py-2">
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <p className="text-xs text-muted-foreground mb-0.5">Timestamp</p>
                  <p className="text-sm font-medium">{detailLog.created_date ? new Date(detailLog.created_date).toLocaleString('en-SG') : '—'}</p>
                </div>
                <div>
                  <p className="text-xs text-muted-foreground mb-0.5">Actor</p>
                  <p className="text-sm font-medium">{detailLog.actor_name || 'System'} <span className="text-xs text-muted-foreground">({detailLog.actor_role})</span></p>
                </div>
                <div>
                  <p className="text-xs text-muted-foreground mb-0.5">Action</p>
                  <p className="text-sm font-medium">{detailLog.action_type?.replace(/_/g, ' ')}</p>
                </div>
                <div>
                  <p className="text-xs text-muted-foreground mb-0.5">Module</p>
                  <p className="text-sm font-medium">{MODULE_LABELS[detailLog.module] || detailLog.module}</p>
                </div>
                <div>
                  <p className="text-xs text-muted-foreground mb-0.5">Target Entity</p>
                  <p className="text-sm font-medium">{detailLog.target_entity}</p>
                </div>
                <div>
                  <p className="text-xs text-muted-foreground mb-0.5">Record ID</p>
                  <p className="text-sm font-mono text-xs">{detailLog.target_record_id}</p>
                </div>
                <div>
                  <p className="text-xs text-muted-foreground mb-0.5">IP Address</p>
                  <p className="text-sm font-mono">{detailLog.ip_address || '—'}</p>
                </div>
                <div>
                  <p className="text-xs text-muted-foreground mb-0.5">Shield Outcome</p>
                  <span className={`inline-flex items-center px-2 py-0.5 rounded-md border text-[10px] font-medium ${SHIELD_STYLES[detailLog.shield_outcome] || SHIELD_STYLES.not_evaluated}`}>
                    {detailLog.shield_outcome?.replace(/_/g, ' ') || 'not evaluated'}
                  </span>
                </div>
              </div>
              {detailLog.details && (
                <div>
                  <p className="text-xs text-muted-foreground mb-1">Details</p>
                  <p className="text-sm bg-muted/50 rounded-lg p-3">{detailLog.details}</p>
                </div>
              )}
              {detailLog.justification && (
                <div>
                  <p className="text-xs text-muted-foreground mb-1">Justification</p>
                  <p className="text-sm bg-amber-500/5 border border-amber-500/20 rounded-lg p-3">{detailLog.justification}</p>
                </div>
              )}
              {detailLog.evidence_urls?.length > 0 && (
                <div>
                  <p className="text-xs text-muted-foreground mb-1">Evidence Attachments</p>
                  <div className="flex flex-wrap gap-2">
                    {detailLog.evidence_urls.map((url, i) => (
                      <a key={i} href={url} target="_blank" rel="noopener noreferrer" className="text-xs text-primary hover:underline flex items-center gap-1 bg-primary/5 px-2 py-1 rounded">
                        <FileText className="w-3 h-3" /> Attachment {i + 1}
                      </a>
                    ))}
                  </div>
                </div>
              )}
              {detailLog.previous_state && (
                <div>
                  <p className="text-xs text-muted-foreground mb-1">Previous State</p>
                  <pre className="text-xs bg-muted/50 rounded-lg p-3 overflow-x-auto">{JSON.stringify(detailLog.previous_state, null, 2)}</pre>
                </div>
              )}
              {detailLog.new_state && (
                <div>
                  <p className="text-xs text-muted-foreground mb-1">New State</p>
                  <pre className="text-xs bg-muted/50 rounded-lg p-3 overflow-x-auto">{JSON.stringify(detailLog.new_state, null, 2)}</pre>
                </div>
              )}
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}