import React, { useState, useMemo } from 'react';
import { useQuery } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import OrbitanLogo from '@/components/layout/OrbitanLogo';
import UserMenu from '@/components/shared/UserMenu';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import EmptyState from '@/components/shared/EmptyState';
import ReactMarkdown from 'react-markdown';
import { BookOpen, Search, FileText, GraduationCap, Shield, ClipboardList, Lightbulb, ArrowLeft, Clock } from 'lucide-react';

const DOC_TYPE_CONFIG = {
  sop:                  { label: 'SOP',              icon: FileText,        color: 'text-orbitan-blue',   bg: 'bg-orbitan-blue-light' },
  training_module:      { label: 'Training',         icon: GraduationCap,   color: 'text-orbitan-purple', bg: 'bg-orbitan-purple-light' },
  policy:               { label: 'Policy',           icon: Shield,          color: 'text-orbitan-red',   bg: 'bg-orbitan-red-light' },
  shift_brief:          { label: 'Shift Brief',      icon: Clock,           color: 'text-orbitan-amber',  bg: 'bg-orbitan-amber-light' },
  incident_report:      { label: 'Incident',         icon: ClipboardList,   color: 'text-destructive',    bg: 'bg-destructive/10' },
  compliance_checklist: { label: 'Checklist',        icon: ClipboardList,   color: 'text-orbitan-green',  bg: 'bg-orbitan-green-light' },
};

export default function KnowledgeHub() {
  const [search, setSearch] = useState('');
  const [typeFilter, setTypeFilter] = useState('all');
  const [selectedDoc, setSelectedDoc] = useState(null);

  const { data: documents = [], isLoading } = useQuery({
    queryKey: ['knowledge-hub-docs'],
    queryFn: () => base44.entities.AIDocument.filter({ status: ['approved', 'auto_published'] }, '-created_date', 200),
  });

  const filtered = useMemo(() => {
    return documents.filter(doc => {
      const matchesType = typeFilter === 'all' || doc.document_type === typeFilter;
      const matchesSearch = !search ||
        doc.title?.toLowerCase().includes(search.toLowerCase()) ||
        doc.content_markdown?.toLowerCase().includes(search.toLowerCase()) ||
        doc.tags?.some(t => t.toLowerCase().includes(search.toLowerCase()));
      return matchesType && matchesSearch;
    });
  }, [documents, search, typeFilter]);

  const typeCounts = useMemo(() => {
    const counts = {};
    documents.forEach(d => {
      counts[d.document_type] = (counts[d.document_type] || 0) + 1;
    });
    return counts;
  }, [documents]);

  // Document reader view
  if (selectedDoc) {
    const config = DOC_TYPE_CONFIG[selectedDoc.document_type] || DOC_TYPE_CONFIG.sop;
    const DocIcon = config.icon;
    return (
      <div className="min-h-screen bg-background flex flex-col">
        <header className="border-b border-border bg-background sticky top-0 z-40 pt-[env(safe-area-inset-top)]">
          <div className="max-w-4xl mx-auto px-4 sm:px-6 py-3 flex items-center justify-between gap-3">
            <div className="flex items-center gap-3">
              <Button variant="ghost" size="icon" className="h-8 w-8" onClick={() => setSelectedDoc(null)}>
                <ArrowLeft className="w-4 h-4" />
              </Button>
              <OrbitanLogo size="sm" showOS />
            </div>
            <div className="w-28"><UserMenu variant="light" /></div>
          </div>
        </header>

        <main className="flex-1 max-w-4xl mx-auto w-full px-4 sm:px-6 py-8">
          <div className="mb-6">
            <div className="flex items-center gap-2 mb-3">
              <div className={`w-8 h-8 rounded-lg flex items-center justify-center ${config.bg}`}>
                <DocIcon className={`w-4 h-4 ${config.color}`} />
              </div>
              <Badge variant="outline" className={`text-xs ${config.color}`}>{config.label}</Badge>
              {selectedDoc.principle && (
                <Badge variant="outline" className="text-xs text-muted-foreground capitalize">
                  {selectedDoc.principle}
                </Badge>
              )}
            </div>
            <h1 className="text-2xl sm:text-3xl font-display font-bold text-foreground mb-2">{selectedDoc.title}</h1>
            <div className="flex items-center gap-3 text-xs text-muted-foreground">
              {selectedDoc.industry_context && <span className="capitalize">{selectedDoc.industry_context.replace(/_/g, ' ')}</span>}
              {selectedDoc.model_used && <span>· Generated by {selectedDoc.model_used}</span>}
              {selectedDoc.version > 1 && <span>· v{selectedDoc.version}</span>}
            </div>
          </div>

          <div className="bg-card border border-border rounded-xl p-6 sm:p-8">
            <div className="prose prose-sm max-w-none prose-headings:font-heading prose-headings:font-semibold prose-table:text-sm prose-th:bg-muted prose-th:px-3 prose-th:py-2 prose-td:px-3 prose-td:py-2 prose-td:border prose-td:border-border">
              <ReactMarkdown>{selectedDoc.content_markdown || 'No content available.'}</ReactMarkdown>
            </div>
          </div>
        </main>
      </div>
    );
  }

  // Document library view
  return (
    <div className="min-h-screen bg-background flex flex-col">
      <header className="border-b border-border bg-background sticky top-0 z-40 pt-[env(safe-area-inset-top)]">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 py-3 flex items-center justify-between gap-3">
          <OrbitanLogo size="sm" showOS />
          <div className="flex items-center gap-3">
            <div className="hidden lg:flex items-center gap-2 bg-muted px-3 py-1.5 rounded-lg text-xs font-semibold text-muted-foreground">
              <BookOpen className="w-3.5 h-3.5" />
              Knowledge Hub
            </div>
            <div className="w-28"><UserMenu variant="light" /></div>
          </div>
        </div>
      </header>

      <main className="flex-1 max-w-7xl mx-auto w-full px-4 sm:px-6 py-8">
        <div className="mb-6">
          <div className="inline-flex items-center gap-2 bg-orbitan-purple-light text-orbitan-purple px-3 py-1.5 rounded-full text-xs font-semibold mb-3">
            <Lightbulb className="w-3.5 h-3.5" />
            OrbitanOS Documentation Portal
          </div>
          <h1 className="text-2xl sm:text-3xl font-display font-bold text-foreground mb-1">Knowledge Hub</h1>
          <p className="text-sm text-muted-foreground">Central library for platform architecture, usage guides, SOPs, and internal product documentation.</p>
        </div>

        {/* Search */}
        <div className="relative mb-4">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
          <Input
            placeholder="Search documents by title, content, or tags…"
            value={search}
            onChange={e => setSearch(e.target.value)}
            className="pl-9 max-w-md"
          />
        </div>

        {/* Type Filters */}
        <div className="flex items-center gap-2 mb-6 flex-wrap">
          <button
            onClick={() => setTypeFilter('all')}
            className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${typeFilter === 'all' ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground hover:bg-accent'}`}
          >
            All ({documents.length})
          </button>
          {Object.entries(DOC_TYPE_CONFIG).map(([type, config]) => {
            const count = typeCounts[type] || 0;
            if (count === 0) return null;
            const Icon = config.icon;
            return (
              <button
                key={type}
                onClick={() => setTypeFilter(type)}
                className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors flex items-center gap-1.5 ${typeFilter === type ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground hover:bg-accent'}`}
              >
                <Icon className="w-3 h-3" />
                {config.label} ({count})
              </button>
            );
          })}
        </div>

        {/* Document Grid */}
        {isLoading ? (
          <div className="py-12 text-center text-sm text-muted-foreground">Loading documents…</div>
        ) : filtered.length === 0 ? (
          <EmptyState icon={BookOpen} title="No documents found" description="Documents will appear here once they are generated and approved." />
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {filtered.map(doc => {
              const config = DOC_TYPE_CONFIG[doc.document_type] || DOC_TYPE_CONFIG.sop;
              const Icon = config.icon;
              const preview = (doc.content_markdown || '').replace(/[#*`>\-\[\]()_!]/g, '').slice(0, 120);
              return (
                <button
                  key={doc.id}
                  onClick={() => setSelectedDoc(doc)}
                  className="text-left bg-card border border-border rounded-xl p-4 hover:shadow-md hover:border-primary/30 transition-all group"
                >
                  <div className="flex items-center gap-2 mb-3">
                    <div className={`w-8 h-8 rounded-lg flex items-center justify-center ${config.bg}`}>
                      <Icon className={`w-4 h-4 ${config.color}`} />
                    </div>
                    <Badge variant="outline" className={`text-[10px] ${config.color}`}>{config.label}</Badge>
                  </div>
                  <h3 className="text-sm font-semibold text-foreground mb-1 line-clamp-2 group-hover:text-primary transition-colors">
                    {doc.title}
                  </h3>
                  <p className="text-xs text-muted-foreground line-clamp-2 mb-2">{preview}…</p>
                  <div className="flex items-center gap-2 flex-wrap">
                    {doc.industry_context && (
                      <span className="text-[10px] text-muted-foreground capitalize">{doc.industry_context.replace(/_/g, ' ')}</span>
                    )}
                    {doc.tags?.slice(0, 2).map((tag, i) => (
                      <span key={i} className="text-[10px] bg-muted text-muted-foreground px-1.5 py-0.5 rounded">{tag}</span>
                    ))}
                  </div>
                </button>
              );
            })}
          </div>
        )}
      </main>
    </div>
  );
}